version: '3.0'

services:

    frontend:
        container_name: frontend
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        environment: 
            - CHOKIDAR_USEPOLLING=true
        ports:
            - '8081:8080'
